export default function TermsPage() {
  const legalStyles = `
    @import url('https://fonts.googleapis.com/css2?family=Syne:wght@400;600;700;800&family=Figtree:wght@300;400;500;600&display=swap');
    .legal-page { min-height:100vh; background:#05050a; font-family:'Figtree',sans-serif; color:#f0f0f8; }
    .legal-hero { position:relative; padding:72px 24px 52px; border-bottom:1px solid rgba(255,255,255,0.07); overflow:hidden; }
    .legal-hero-bg { position:absolute; inset:0; pointer-events:none; background:radial-gradient(ellipse 50% 40% at 50% 0%, rgba(59,107,255,0.1) 0%, transparent 60%); }
    .legal-hero-inner { position:relative; z-index:1; max-width:760px; margin:0 auto; }
    .legal-eyebrow { font-size:11px; font-weight:600; letter-spacing:0.14em; text-transform:uppercase; color:rgba(240,240,248,0.3); margin-bottom:16px; display:block; }
    .legal-title { font-family:'Syne',sans-serif; font-size:clamp(32px,5vw,52px); font-weight:800; line-height:1; letter-spacing:-0.04em; color:#f0f0f8; margin-bottom:12px; }
    .legal-date { font-size:13px; color:rgba(240,240,248,0.3); }
    .legal-main { max-width:760px; margin:0 auto; padding:52px 24px 96px; }
    .legal-section { margin-bottom:40px; }
    .legal-h2 { font-family:'Syne',sans-serif; font-size:18px; font-weight:700; color:#f0f0f8; margin-bottom:14px; letter-spacing:-0.02em; display:flex; align-items:center; gap:10px; }
    .legal-h2::before { content:''; display:block; width:3px; height:18px; background:linear-gradient(to bottom,#3b6bff,#00d4aa); border-radius:2px; flex-shrink:0; }
    .legal-p { font-size:15px; color:rgba(240,240,248,0.5); line-height:1.8; font-weight:300; margin-bottom:12px; }
    .legal-p:last-child { margin-bottom:0; }
    .legal-divider { height:1px; background:rgba(255,255,255,0.07); margin:36px 0; }
    .legal-link { color:#7da4ff; text-decoration:none; }
    .legal-link:hover { color:#b8ccff; }
  `;

  return (
    <>
      <style>{legalStyles}</style>
      <div className="legal-page">
        <header className="legal-hero">
          <div className="legal-hero-bg" />
          <div className="legal-hero-inner">
            <span className="legal-eyebrow">Legal Document</span>
            <h1 className="legal-title">Terms of Service</h1>
            <p className="legal-date">Last Updated: February 2026</p>
          </div>
        </header>
        <main className="legal-main">
          <div className="legal-section">
            <h2 className="legal-h2">1. Acceptance of Terms</h2>
            <p className="legal-p">By accessing and using the Infalex website and its suite of utilities — including but not limited to Resumetra, DocuMind RAG, and PhishGuard — you accept and agree to be bound by the terms and provisions of this agreement. If you do not agree to abide by these terms, please do not use our services.</p>
          </div>
          <div className="legal-divider" />
          <div className="legal-section">
            <h2 className="legal-h2">2. Description of Service and AI Limitations</h2>
            <p className="legal-p">Infalex provides a variety of artificial intelligence and developer tools. Due to the probabilistic nature of machine learning algorithms, the output generated by our services may not always be 100% accurate, complete, or reliable. Users must independently verify any critical information, especially regarding career, security, or agricultural decisions.</p>
          </div>
          <div className="legal-divider" />
          <div className="legal-section">
            <h2 className="legal-h2">3. User Responsibilities</h2>
            <p className="legal-p">You agree to use our services only for lawful purposes. You must not use the platform to generate illegal, harmful, or abusive content. You are responsible for maintaining the confidentiality of any account credentials and for all activities that occur under your account.</p>
          </div>
          <div className="legal-divider" />
          <div className="legal-section">
            <h2 className="legal-h2">4. Intellectual Property</h2>
            <p className="legal-p">All content, features, and functionality on the Infalex platform — including text, graphics, logos, and software code — are the exclusive property of Infalex and are protected by international copyright, trademark, and other intellectual property laws. You retain ownership of any personal data or documents you upload to our tools.</p>
          </div>
          <div className="legal-divider" />
          <div className="legal-section">
            <h2 className="legal-h2">5. Limitation of Liability</h2>
            <p className="legal-p">In no event shall Infalex, nor its developers, be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the service.</p>
          </div>
        </main>
      </div>
    </>
  );
}