export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <header className="pt-24 pb-12 border-b border-slate-100 bg-slate-50/50">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <h1 className="text-4xl font-bold tracking-tight text-slate-900 mb-4">Terms of Service</h1>
          <p className="text-slate-500 font-medium leading-relaxed">
            Brief: These terms govern your use of Infalex. By accessing our platform, you agree to abide by these rules and understand the limitations of AI-generated content.
          </p>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <article className="prose prose-slate prose-a:text-blue-600 hover:prose-a:text-blue-500 max-w-none">
          <h2>1. Acceptance of Terms</h2>
          <p>
            By accessing and using the Infalex website and its suite of utilities (including but not limited to Resume Matcher, DocuMind RAG, and PhishGuard), you accept and agree to be bound by the terms and provisions of this agreement. If you do not agree to abide by these terms, please do not use our services.
          </p>

          <h2>2. Description of Service and AI Limitations</h2>
          <p>
            Infalex provides a variety of artificial intelligence and developer tools. Due to the probabilistic nature of machine learning algorithms, the output generated by our services may not always be 100% accurate, complete, or reliable. Users must independently verify any critical information, especially regarding career, security, or agricultural decisions.
          </p>

          <h2>3. User Responsibilities</h2>
          <p>
            You agree to use our services only for lawful purposes. You must not use the platform to generate illegal, harmful, or abusive content. You are responsible for maintaining the confidentiality of any account credentials and for all activities that occur under your account.
          </p>

          <h2>4. Intellectual Property</h2>
          <p>
            All content, features, and functionality on the Infalex platform—including text, graphics, logos, and software code—are the exclusive property of Infalex and are protected by international copyright, trademark, and other intellectual property laws. You retain ownership of any personal data or documents you upload to our tools.
          </p>

          <h2>5. Limitation of Liability</h2>
          <p>
            In no event shall Infalex, nor its developers, be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the service.
          </p>

          <p className="text-sm text-slate-400 mt-8"><em>Last Updated: February 2026</em></p>
        </article>
      </main>
    </div>
  );
}