import type { Metadata } from "next";
import { LegalPageLayout } from "../../components/layout/LegalPageLayout";

export const metadata: Metadata = {
  title: "Terms of Service | Infalex",
  description: "Terms of Service and usage policies for the Infalex platform.",
};

export default function TermsPage() {
  return (
    <LegalPageLayout title="Terms of Service" description="Terms of Service and usage policies for the Infalex platform." lastUpdated="February 2026">
      <h2>1. Acceptance of Terms</h2>
      <p>By accessing and using the Infalex website and its suite of utilities — including but not limited to Resumetra, DocuMind RAG, and PhishGuard — you accept and agree to be bound by the terms and provisions of this agreement. If you do not agree to abide by these terms, please do not use our services.</p>
      
      <h2>2. Description of Service and AI Limitations</h2>
      <p>Infalex provides a variety of artificial intelligence and developer tools. Due to the probabilistic nature of machine learning algorithms, the output generated by our services may not always be 100% accurate, complete, or reliable. Users must independently verify any critical information, especially regarding career, security, or agricultural decisions.</p>

      <h2>3. User Responsibilities</h2>
      <p>You agree to use our services only for lawful purposes. You must not use the platform to generate illegal, harmful, or abusive content. You are responsible for maintaining the confidentiality of any account credentials and for all activities that occur under your account.</p>

      <h2>4. Intellectual Property</h2>
      <p>All content, features, and functionality on the Infalex platform — including text, graphics, logos, and software code — are the exclusive property of Infalex and are protected by international copyright, trademark, and other intellectual property laws. You retain ownership of any personal data or documents you upload to our tools.</p>

      <h2>5. Limitation of Liability</h2>
      <p>In no event shall Infalex, nor its developers, be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the service.</p>
    </LegalPageLayout>
  );
}